# Generated by Django 3.2.2 on 2023-03-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230328_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
