# Generated by Django 3.2.2 on 2023-05-31 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230531_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='id',
            new_name='store',
        ),
    ]
