# Generated by Django 3.2.2 on 2023-03-30 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230328_0804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='state',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zipcode',
        ),
    ]
