# Generated by Django 3.2.2 on 2023-03-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20230330_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='store',
        ),
        migrations.AddField(
            model_name='address',
            name='id',
            field=models.IntegerField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
